# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes: 
      - /opt/postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /data/postgres
      POSTGRES_DB: monster-compendium-db